---

- name: Create Patch directory
  file:
    path: "{{ patch_directory }}"
    state: directory
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"

- name: copy psu patch file 
  copy:
    src: "{{ oracle_stage_base }}/{{ oracle_version }}/{{ patch_name }}/{{ quarterly_patches[oracle_version][patch_name].filename }}"
    dest: "{{ oracle_stage_install }}"
  #with_items: "{{ quarterly_patches[oracle_version][patch_name].filename }}"

- name: copy one-off patch file
  copy:
    src: "{{ oracle_stage_base }}/{{ oracle_version }}/{{ patch_name }}//{{ item.filename }}"
    dest: "{{ oracle_stage_install }}"
  with_items: "{{ oneoff_patches[oracle_version]|default([]) }}"
  when: not rollback_psu

- name: Check for PSU zip file
  stat:
    path: "{{ oracle_stage_install }}/{{ quarterly_patches[oracle_version][patch_name].filename }}"
    get_checksum: false
    get_md5: false
  register: psu_patch_st
  failed_when: not psu_patch_st.stat.exists
  when: not rollback_psu

- name: Check for one-off zip file
  stat:
    path: "{{ oracle_stage_install }}/{{ item.filename }}"
    get_checksum: false
    get_md5: false
  register: patch_st
  failed_when: not  patch_st.stat.exists 
  with_items: "{{ oneoff_patches[oracle_version]|default([]) }}"
  when: not rollback_psu

- name: Check PSU zip file for Rollback
  stat:
    path: "{{ oracle_stage_install }}/{{ quarterly_patches[oracle_version][patch_name].filename }}"
    get_checksum: false
    get_md5: false
  register: psu_patch_st
  failed_when: not psu_patch_st.stat.exists
  when: rollback_psu

- name: Unzip Quarterly Patch
  unarchive:
    src: "{{ oracle_stage_install }}/{{ quarterly_patches[oracle_version][patch_name].filename }}"
    dest: "{{ patch_directory}}/"
    copy: no
    creates: "{{ patch_directory }}/{{ quarterly_patches[oracle_version][patch_name].patchid }}/"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
  when: not rollback_psu

- name: Unzip One-Off Patch
  unarchive:
    src: "{{ oracle_stage_install }}/{{ item.filename }}"
    dest: "{{ patch_directory}}/"
    copy: no
    creates: "{{ patch_directory }}/{{ item.filename }}/"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
  with_items: "{{ oneoff_patches[oracle_version]|default([]) }}"
  when: not rollback_psu


- name: Unzip Quarterly Patch for rollback
  unarchive:
    src: "{{ oracle_stage_install }}/{{ quarterly_patches[oracle_version][patch_name].filename }}"
    dest: "{{ patch_directory}}/"
    copy: no
    creates: "{{ patch_directory }}/{{ quarterly_patches[oracle_version][patch_name].patchid }}/"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
  when: rollback_psu


