---
#Apply One-Off patches
- name: Template one-off patch list
  template:
    src: patch_list.j2
    dest: "{{ oracle_stage_install }}/patch_list.txt"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"

- name: Opatch prereq check for one-off patches
  shell: opatch prereq CheckConflictAgainstOHWithDetail -phBaseFile {{ oracle_stage_install }}/patch_list.txt
  environment: "{{ env }}"
  register: conflictsoneoff
  async: 900 
  poll: 120

- debug:
    msg: "{{ conflictsoneoff }}"
  tags: debug

- name: Apply one-off patches
  shell: opatch napply -force -silent -skip_subset -skip_duplicate -phBaseFile {{ oracle_stage_install }}/patch_list.txt
  environment: "{{ env }}"
  register: applyoneoff
  async: 900 
  poll: 120

- debug:
    msg: "{{ applyoneoff }}"
  tags: debug
